### ISSUE TITLE
Wie öffnet man die Java-Datei?

### ISSUE THREAD

**Issue by wisnox** [Devoxx4KidsDE/workshop-jumping-sumo#1]
Hallo
Ich habe nicht viel Ahnung von Java, aber wie öffnet man die Datei Jumpingsumo.jar?
Zunächst habe ich dir rar.Datei in einen Ordner gelegt und dann bei [Öffnen mit] Java Environment ausgewählt.
Aber irgendwie erscheint nur ein weißer Kasten ohne Inhalt.

Muss man die Datei über cmd öffnen, und wenn ja wie ?

Beste Grüße 
Wisam

**Comment by daschJulia** [comment]
das issue ist nun schon paar Jahre alt ich schließ es.
Falls immer noch ein Problem besteht, kannst du gern ein neues Issue auf machen.
